---
# Kube Prometheus Stack Configuration
# Optimized for Talos homelab cluster with manual DNS management

# Global settings
global:
  rbac:
    create: true
    pspEnabled: false

# Alertmanager configuration
alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - alertmanager.${SECRET_DOMAIN}
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.${SECRET_DOMAIN}
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

# Grafana configuration
grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: ${SECRET_GRAFANA_PASSWORD}
  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - grafana.${SECRET_DOMAIN}
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.${SECRET_DOMAIN}
  persistence:
    enabled: true
    storageClassName: ceph-block
    size: 10Gi
  grafana.ini:
    server:
      root_url: "https://grafana.${SECRET_DOMAIN}"
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: true
      org_role: Viewer
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/kubernetes-cluster-monitoring_rev1.json

# Prometheus configuration
prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - prometheus.${SECRET_DOMAIN}
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.${SECRET_DOMAIN}
  prometheusSpec:
    retention: 7d
    retentionSize: 10GB
    walCompression: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    # Monitor all namespaces
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    # Add Talos-specific scrape configs
    additionalScrapeConfigs:
      - job_name: 'talos-nodes'
        static_configs:
          - targets:
              - '192.168.1.2:9100'  # Control plane
              - '192.168.1.3:9100'  # Worker
        metrics_path: /metrics
        scrape_interval: 15s

# Node Exporter
nodeExporter:
  enabled: true

# Kube State Metrics
kubeStateMetrics:
  enabled: true

# Prometheus Operator
prometheusOperator:
  enabled: true
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false

# Disable components we don't need in homelab
kubeApiServer:
  enabled: true
kubelet:
  enabled: true
kubeControllerManager:
  enabled: false  # Not available in Talos
kubeScheduler:
  enabled: false  # Not available in Talos
kubeProxy:
  enabled: false  # Using Cilium
kubeEtcd:
  enabled: false  # Not accessible in Talos
