---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${SECRET_LETSENCRYPT_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      # HTTP-01 challenge for manual DNS management
      - http01:
          ingress:
            class: cilium
        selector:
          dnsNames:
            - "${SECRET_DOMAIN}"
            - "*.${SECRET_DOMAIN}"
---
# Staging issuer for testing
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${SECRET_LETSENCRYPT_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: cilium
        selector:
          dnsNames:
            - "${SECRET_DOMAIN}"
            - "*.${SECRET_DOMAIN}"
