---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  # Email for Let's Encrypt registration
  email: ENC[AES256_GCM,data:example_encrypted_email,type:str]
