---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/kustomization.yaml
  - ./default/kustomization.yaml
  - ./kube-system/kustomization.yaml
  - ./monitoring/kustomization.yaml
  - ./network/kustomization.yaml
